import { NextRequest, NextResponse } from "next/server";
import dbConnect from "@/lib/mongoose";
import Article from "@/models/Article";

// This cron job previously archived old auto-generated history articles.
// Archiving has been DISABLED - all history articles stay published permanently.
// The endpoint now restores any previously archived auto-generated articles back to published.

export async function GET(request: NextRequest) {
  try {
    const authHeader = request.headers.get("authorization");
    const cronSecret = process.env.CRON_SECRET;
    
    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await dbConnect();

    // Restore all previously archived auto-generated articles back to published
    const result = await Article.updateMany(
      {
        $or: [
          { tags: 'on-this-day' },
          { autoGenerated: true }
        ],
        status: 'archived'
      },
      {
        $set: { status: 'published' }
      }
    );

    return NextResponse.json({
      success: true,
      message: `Archiving disabled. Restored ${result.modifiedCount} articles to published.`,
      restoredCount: result.modifiedCount,
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed to restore articles";
    console.error("archive-old-articles cron error:", message);
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
