import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/mongoose';
import Article from '@/models/Article';

// Fix: clear scheduledAt from published articles AND fix category for AI-generated history articles
export async function POST(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  if (searchParams.get('secret') !== 'migrate2025') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  // 1. Clear scheduledAt from all published articles (moves them from "Scheduled" → "Published" tab in admin)
  const clearScheduled = await Article.updateMany(
    { status: 'published', scheduledAt: { $exists: true, $ne: null } },
    { $unset: { scheduledAt: '' } }
  );

  // 2. Fix category for AI-generated articles with "Month Day:" title pattern that have wrong category
  // These are the daily history articles - should always be 'history'
  const fixCategory = await Article.updateMany(
    {
      autoGenerated: true,
      category: { $ne: 'history' },
      title: { $regex: /^(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d+:/i }
    },
    { $set: { category: 'history' } }
  );

  return NextResponse.json({
    success: true,
    scheduledAtCleared: clearScheduled.modifiedCount,
    categoryFixed: fixCategory.modifiedCount,
  });
}
