import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/mongoose';
import Article from '@/models/Article';
import User from '@/models/User';

// POST - Fix authorName/authorAvatar for articles
// ?mode=all - Fix ALL articles with wrong author (not just autoGenerated)
// ?mode=auto - Fix only autoGenerated articles (default)
export async function POST(request: NextRequest) {
  try {
    await dbConnect();
    
    const { searchParams } = new URL(request.url);
    const mode = searchParams.get('mode') || 'auto';
    const targetAuthorName = searchParams.get('from') || 'Noodles'; // Author name to fix
    
    // Find articles to fix
    let query: any = {};
    if (mode === 'all') {
      // Fix ALL articles where authorName matches target
      query = { authorName: targetAuthorName };
    } else {
      // Fix only autoGenerated articles
      query = { autoGenerated: true };
    }
    
    const articles = await Article.find(query).select('_id author authorName').lean();

    if (articles.length === 0) {
      return NextResponse.json({ success: true, message: 'No articles to fix', fixed: 0 });
    }

    // Get all AI reporters
    const aiReporters = await User.find({ isAIReporter: true })
      .select('_id username displayName avatar')
      .lean();
    
    const reporterMap = new Map(aiReporters.map((u: any) => [
      u._id.toString(), 
      { 
        name: u.displayName || u.username || 'BOGX Team',
        avatar: u.avatar || ''
      }
    ]));

    // Update each article - if author is an AI reporter, use their name
    // Otherwise set to "BOGX Team"
    let fixed = 0;
    const updates: string[] = [];
    
    for (const article of articles) {
      const authorId = (article as any).author?.toString();
      const reporterData = authorId ? reporterMap.get(authorId) : null;
      
      // Use reporter name if author is AI reporter, otherwise "BOGX Team"
      const newName = reporterData?.name || 'BOGX Team';
      const newAvatar = reporterData?.avatar || '';
      
      if ((article as any).authorName !== newName) {
        await Article.updateOne(
          { _id: article._id },
          { 
            $set: { 
              authorName: newName,
              authorAvatar: newAvatar
            }
          }
        );
        updates.push(`${(article as any).authorName} → ${newName}`);
        fixed++;
      }
    }

    return NextResponse.json({ 
      success: true, 
      message: `Fixed ${fixed} articles`,
      fixed,
      updates,
      aiReporters: aiReporters.map((r: any) => ({ id: r._id.toString(), name: r.displayName || r.username }))
    });
  } catch (error: any) {
    console.error('Fix article authors error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
