import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

async function check() {
  await mongoose.connect(process.env.MONGODB_URI || '');

  console.log('=== Recent "history" articles (autoGenerated) ===');
  const articles = await mongoose.connection.collection('articles')
    .find({ category: 'history', autoGenerated: true })
    .sort({ createdAt: -1 })
    .limit(10)
    .toArray();
  for (const a of articles) {
    console.log(`${a.createdAt?.toISOString()} - "${a.title}" - status: ${a.status}`);
  }

  console.log('\n=== Recent DailyFact entries ===');
  const facts = await mongoose.connection.collection('dailyfacts')
    .find({})
    .sort({ createdAt: -1 })
    .limit(10)
    .toArray();
  for (const f of facts) {
    console.log(`dateKey: ${f.dateKey} - createdAt: ${f.createdAt?.toISOString()} - hasFacts: ${!!f.welcome?.facts?.length}`);
  }

  await mongoose.disconnect();
}
check();
