import mongoose from 'mongoose';

export interface IArticle {
  _id?: string;
  title: string;
  subtitle?: string;
  content: string; // HTML content
  coverImage?: string;
  imageScale?: number; // 50-100, percentage of image size
  imagePosition?: 'top' | 'center' | 'bottom' | 'left' | 'right'; // Where to focus the image
  imagePosX?: number; // 0-100, horizontal position
  imagePosY?: number; // 0-100, vertical position
  contentType: 'article' | 'rankroll' | 'tv' | 'radio' | 'arcade' | 'shop'; // Type of content
  linkedContentId?: string; // ID of linked Poll, TVVideo, RadioStation, etc.
  mainCategory: string; // Main category (articles, arcade, voting, shop)
  category: string;     // Sub category (music, culture, gaming, etc.)
  tags: string[];
  author: mongoose.Types.ObjectId; // Admin user who created it
  authorName?: string; // Cached author name for display
  authorAvatar?: string; // Cached author avatar URL
  status: 'draft' | 'published' | 'archived';
  layout: 'featured' | 'trending' | 'standard'; // Display layout type
  order: number; // Display order (lower = higher on page)
  featured: boolean; // Show prominently in feed
  trending: boolean; // Mark as trending
  views: number;
  likes: number;
  publishedAt?: Date;
  scheduledAt?: Date;
  commentsEnabled?: boolean;
  autoGenerated?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  // Styling options
  titleColor?: string;
  titleFont?: 'default' | 'display' | 'serif' | 'mono';
  subtitleColor?: string;
  contentColor?: string;
}

const ArticleSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200,
  },
  subtitle: {
    type: String,
    trim: true,
    maxlength: 300,
  },
  content: {
    type: String,
    required: true,
  },
  coverImage: {
    type: String,
    default: '',
  },
  thumbnailUrl: {
    type: String,
    default: '',
  },
  galleryImages: {
    type: [String],
    default: [],
  },
  imageScale: {
    type: Number,
    default: 100,
    min: 50,
    max: 100,
  },
  imagePosition: {
    type: String,
    enum: ['top', 'center', 'bottom', 'left', 'right'],
    default: 'center',
  },
  imagePosX: {
    type: Number,
    default: 50,
    min: 0,
    max: 100,
  },
  imagePosY: {
    type: Number,
    default: 50,
    min: 0,
    max: 100,
  },
  contentType: {
    type: String,
    enum: ['article', 'rankroll', 'tv', 'radio', 'arcade', 'shop'],
    default: 'article',
  },
  linkedContentId: {
    type: String, // ID of linked Poll, TVVideo, RadioStation, ArcadeGame, etc.
    default: null,
  },
  mainCategory: {
    type: String,
    required: true,
    enum: ['articles', 'arcade', 'voting', 'shop'],
    default: 'articles',
  },
  category: {
    type: String,
    required: true,
    enum: ['movies-tv', 'music', 'gaming', 'sports', 'tech', 'culture', 'news', 'lifestyle', 'genx-icons'],
    default: 'culture',
  },
  tags: {
    type: [String],
    default: [],
  },
  author: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  authorName: {
    type: String,
    default: 'BOGX Team',
  },
  authorAvatar: {
    type: String,
    default: '',
  },
  status: {
    type: String,
    enum: ['draft', 'published', 'archived'],
    default: 'draft',
  },
  layout: {
    type: String,
    enum: ['featured', 'trending', 'standard'],
    default: 'standard',
  },
  order: {
    type: Number,
    default: 0,
  },
  featured: {
    type: Boolean,
    default: false,
  },
  trending: {
    type: Boolean,
    default: false,
  },
  views: {
    type: Number,
    default: 0,
  },
  likes: {
    type: Number,
    default: 0,
  },
  publishedAt: {
    type: Date,
  },
  scheduledAt: {
    type: Date,
  },
  commentsEnabled: {
    type: Boolean,
    default: true,
  },
  autoGenerated: {
    type: Boolean,
    default: false,
  },
  // Styling options
  titleColor: {
    type: String,
    default: '#ffffff',
  },
  titleFont: {
    type: String,
    enum: ['default', 'display', 'serif', 'mono'],
    default: 'default',
  },
  subtitleColor: {
    type: String,
    default: '#9ca3af',
  },
  contentColor: {
    type: String,
    default: '#374151',
  },
}, {
  timestamps: true,
});

// Index for efficient queries
ArticleSchema.index({ status: 1, publishedAt: -1 });
ArticleSchema.index({ status: 1, order: 1, createdAt: -1 }); // For main listing query
ArticleSchema.index({ mainCategory: 1, status: 1 });
ArticleSchema.index({ category: 1, status: 1 });
ArticleSchema.index({ featured: 1, status: 1 });
ArticleSchema.index({ trending: 1, status: 1 });
ArticleSchema.index({ tags: 1 });

// Calculate read time before saving
ArticleSchema.pre('save', function() {
});

export default mongoose.models.Article || mongoose.model<IArticle>('Article', ArticleSchema);
